[2025-04-02T08:06:05.257+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [queued]>
[2025-04-02T08:06:05.261+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [queued]>
[2025-04-02T08:06:05.262+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-02T08:06:05.266+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 08:00:00+00:00
[2025-04-02T08:06:05.272+0000] {standard_task_runner.py:60} INFO - Started process 1059 to run task
[2025-04-02T08:06:05.275+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_c', 'load_data', 'scheduled__2025-04-01T08:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmpx5k_1d89']
[2025-04-02T08:06:05.276+0000] {standard_task_runner.py:88} INFO - Job 56: Subtask load_data
[2025-04-02T08:06:05.308+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [running]> on host f4b0101fc635
[2025-04-02T08:06:05.345+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_c' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T08:00:00+00:00'
[2025-04-02T08:06:05.350+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-02T08:06:05.484+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-02T08:06:05.490+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_c, task_id=load_data, execution_date=20250401T080000, start_date=20250402T080605, end_date=20250402T080605
[2025-04-02T08:06:05.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-02T08:06:05.543+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T10:26:32.523+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [queued]>
[2025-04-02T10:26:32.528+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [queued]>
[2025-04-02T10:26:32.528+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-02T10:26:32.533+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 08:00:00+00:00
[2025-04-02T10:26:32.541+0000] {standard_task_runner.py:60} INFO - Started process 160 to run task
[2025-04-02T10:26:32.544+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_c', 'load_data', 'scheduled__2025-04-01T08:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmp5zp_1orl']
[2025-04-02T10:26:32.545+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask load_data
[2025-04-02T10:26:32.576+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_c.load_data scheduled__2025-04-01T08:00:00+00:00 [running]> on host 247d35c01501
[2025-04-02T10:26:32.614+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_c' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T08:00:00+00:00'
[2025-04-02T10:26:32.618+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-02T10:26:32.752+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-02T10:26:32.756+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_c, task_id=load_data, execution_date=20250401T080000, start_date=20250402T102632, end_date=20250402T102632
[2025-04-02T10:26:32.801+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-02T10:26:32.813+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
